# SQL Introduction

In this lecture we will learn to write SQL queries. SQL can be used within the Python Environment itself.

We will be using the **sqlite3** package in Python. The documentation can be found here: https://docs.python.org/3/library/sqlite3.html

We will use the SAKILA database which is available from Github from the following link: https://github.com/bradleygrant/sakila-sqlite3/tree/main

The Sakila database is a nicely normalised database modelling a DVD rental store. The documentation can be found in the following link:
https://dev.mysql.com/doc/sakila/en/sakila-introduction.html

## Dataset Preparation:

1. Download the `sakila_master.database` from the github link above by clicking on `Ready-To-Use SQLite3 Database File`.
2. Upload the file into Google Drive if you are using google colab.
3. Upload google drive using below code: <br>
`from google.colab import drive` <br>
`drive.mount('/content/drive')`
4. Import packages:
`pandas, sqlite3, numpy, matplotlib`

In [2]:
# run this if using google colab
# ## Mounting google drive ###

# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
# Importing Packages:

import numpy as np # linear algebra
import pandas as pd # data processing (e.g. pd.read_csv)
import sqlite3
import matplotlib.pyplot as plt

In [4]:
# run this if using google colab
### Pathname of the database file to be opened ###
path = "C:/Users/orrru/Documents/GitHub/The-Python-Bible-according-to-UvA-/8. Computer Systems & Engineering/Week 2"  #Insert path here
database = path + 'sakila_master.db'

In [5]:
## if using Jupyter Notebook
## first download the database and put it in the same folder as this Jupyter notebook
## then run this cell
## Path to your SQLite database file (same folder as Jupyter notebook)
database = "sakila_master.db"

# Create SQLite database:

connect() opens a connection to the SQLite database file database. By default returns a Connection object, unless a custom factory is given.

Syntax: `sqlite3.connect(database[, timeout, detect_types, isolation_level, check_same_thread, factory, cached_statements, uri])`

where, database -> database is a path-like object which is pathname of the database file to be opened.

In [6]:
### Connecting to database and checking tables ###

connection_db = sqlite3.connect(database)

## pd.read_sql() executes a query and returns the result in a pandas DataFrame
tables = pd.read_sql("""SELECT *
                        FROM sqlite_master  -- sqlite_master is a special, system table in SQLite that holds metadata of the database
                        WHERE type='table';""", connection_db)

In [7]:
print(tables['name'])

0             actor
1           country
2              city
3           address
4          language
5          category
6          customer
7              film
8        film_actor
9     film_category
10        film_text
11        inventory
12            staff
13            store
14          payment
15           rental
Name: name, dtype: object

# Cursor Object:

It is an object that is used to make the connection for executing SQL queries. It acts as middleware between SQLite database connection and SQL query. It is created after giving connection to SQLite database.

Syntax: `Syntax: cursor_object=connection_object.execute(“sql query”);`

In [8]:
cursor = connection_db.execute('''
SELECT *
FROM sqlite_master
WHERE type='table';
''')
num = 0
for row in cursor:
    print(num, row)
    num = num + 1

0 ('table', 'actor', 'actor', 2, 'CREATE TABLE actor (\n  actor_id numeric NOT NULL ,\n  first_name VARCHAR(45) NOT NULL,\n  last_name VARCHAR(45) NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY  (actor_id)\n  )')
1 ('table', 'country', 'country', 5, 'CREATE TABLE country (\n  country_id SMALLINT NOT NULL,\n  country VARCHAR(50) NOT NULL,\n  last_update TIMESTAMP,\n  PRIMARY KEY  (country_id)\n)')
2 ('table', 'city', 'city', 9, 'CREATE TABLE city (\n  city_id int NOT NULL,\n  city VARCHAR(50) NOT NULL,\n  country_id SMALLINT NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY  (city_id),\n  CONSTRAINT fk_city_country FOREIGN KEY (country_id) REFERENCES country (country_id) ON DELETE NO ACTION ON UPDATE CASCADE\n)')
3 ('table', 'address', 'address', 13, 'CREATE TABLE address (\n  address_id int NOT NULL,\n  address VARCHAR(50) NOT NULL,\n  address2 VARCHAR(50) DEFAULT NULL,\n  district VARCHAR(20) NOT NULL,\n  city_id INT  NOT NULL,\n  postal_code VARCHAR(10) DEFAULT NULL,\n  phone VARCHAR(20) NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY  (address_id),\n  CONSTRAINT fk_address_city FOREIGN KEY (city_id) REFERENCES city (city_id) ON DELETE NO ACTION ON UPDATE CASCADE\n)')
4 ('table', 'language', 'language', 17, 'CREATE TABLE language (\n  language_id SMALLINT NOT NULL ,\n  name CHAR(20) NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY (language_id)\n)')
5 ('table', 'category', 'category', 19, 'CREATE TABLE category (\n  category_id SMALLINT NOT NULL,\n  name VARCHAR(25) NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY  (category_id)\n)')
6 ('table', 'customer', 'customer', 22, "CREATE TABLE customer (\n  customer_id INT NOT NULL,\n  store_id INT NOT NULL,\n  first_name VARCHAR(45) NOT NULL,\n  last_name VARCHAR(45) NOT NULL,\n  email VARCHAR(50) DEFAULT NULL,\n  address_id INT NOT NULL,\n  active CHAR(1) DEFAULT 'Y' NOT NULL,\n  create_date TIMESTAMP NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY  (customer_id),\n  CONSTRAINT fk_customer_store FOREIGN KEY (store_id) REFERENCES store (store_id) ON DELETE NO ACTION ON UPDATE CASCADE,\n  CONSTRAINT fk_customer_address FOREIGN KEY (address_id) REFERENCES address (address_id) ON DELETE NO ACTION ON UPDATE CASCADE\n)")
7 ('table', 'film', 'film', 29, "CREATE TABLE film (\n  film_id int NOT NULL,\n  title VARCHAR(255) NOT NULL,\n  description BLOB SUB_TYPE TEXT DEFAULT NULL,\n  release_year VARCHAR(4) DEFAULT NULL,\n  language_id SMALLINT NOT NULL,\n  original_language_id SMALLINT DEFAULT NULL,\n  rental_duration SMALLINT  DEFAULT 3 NOT NULL,\n  rental_rate DECIMAL(4,2) DEFAULT 4.99 NOT NULL,\n  length SMALLINT DEFAULT NULL,\n  replacement_cost DECIMAL(5,2) DEFAULT 19.99 NOT NULL,\n  rating VARCHAR(10) DEFAULT 'G',\n  special_features VARCHAR(100) DEFAULT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY  (film_id),\n  CONSTRAINT CHECK_special_features CHECK(special_features is null or\n                                                           special_features like '%Trailers%' or\n                                                           special_features like '%Commentaries%' or\n                                                           special_features like '%Deleted Scenes%' or\n                                                           special_features like '%Behind the Scenes%'),\n  CONSTRAINT CHECK_special_rating CHECK(rating in ('G','PG','PG-13','R','NC-17')),\n  CONSTRAINT fk_film_language FOREIGN KEY (language_id) REFERENCES language (language_id) ,\n  CONSTRAINT fk_film_language_original FOREIGN KEY (original_language_id) REFERENCES language (language_id)\n)")
8 ('table', 'film_actor', 'film_actor', 35, 'CREATE TABLE film_actor (\n  actor_id INT NOT NULL,\n  film_id  INT NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY  (actor_id,film_id),\n  CONSTRAINT fk_film_actor_actor FOREIGN KEY (actor_id) REFERENCES actor (actor_id) ON DELETE NO ACTION ON UPDATE CASCADE,\n  CONSTRAINT fk_film_actor_film FOREIGN KEY (film_id) REFERENCES film (film_id) ON DELETE NO ACTION ON UPDATE CASCADE\n)')
9 ('table', 'film_category', 'film_category', 40, 'CREATE TABLE film_category (\n  film_id INT NOT NULL,\n  category_id SMALLINT  NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY (film_id, category_id),\n  CONSTRAINT fk_film_category_film FOREIGN KEY (film_id) REFERENCES film (film_id) ON DELETE NO ACTION ON UPDATE CASCADE,\n  CONSTRAINT fk_film_category_category FOREIGN KEY (category_id) REFERENCES category (category_id) ON DELETE NO ACTION ON UPDATE CASCADE\n)')
10 ('table', 'film_text', 'film_text', 45, 'CREATE TABLE film_text (\n  film_id SMALLINT NOT NULL,\n  title VARCHAR(255) NOT NULL,\n  description BLOB SUB_TYPE TEXT,\n  PRIMARY KEY  (film_id)\n)')
11 ('table', 'inventory', 'inventory', 47, 'CREATE TABLE inventory (\n  inventory_id INT NOT NULL,\n  film_id INT NOT NULL,\n  store_id INT NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY  (inventory_id),\n  CONSTRAINT fk_inventory_store FOREIGN KEY (store_id) REFERENCES store (store_id) ON DELETE NO ACTION ON UPDATE CASCADE,\n  CONSTRAINT fk_inventory_film FOREIGN KEY (film_id) REFERENCES film (film_id) ON DELETE NO ACTION ON UPDATE CASCADE\n)')
12 ('table', 'staff', 'staff', 53, 'CREATE TABLE staff (\n  staff_id SMALLINT NOT NULL,\n  first_name VARCHAR(45) NOT NULL,\n  last_name VARCHAR(45) NOT NULL,\n  address_id INT NOT NULL,\n  picture BLOB DEFAULT NULL,\n  email VARCHAR(50) DEFAULT NULL,\n  store_id INT NOT NULL,\n  active SMALLINT DEFAULT 1 NOT NULL,\n  username VARCHAR(16) NOT NULL,\n  password VARCHAR(40) DEFAULT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY  (staff_id),\n  CONSTRAINT fk_staff_store FOREIGN KEY (store_id) REFERENCES store (store_id) ON DELETE NO ACTION ON UPDATE CASCADE,\n  CONSTRAINT fk_staff_address FOREIGN KEY (address_id) REFERENCES address (address_id) ON DELETE NO ACTION ON UPDATE CASCADE\n)')
13 ('table', 'store', 'store', 58, 'CREATE TABLE store (\n  store_id INT NOT NULL,\n  manager_staff_id SMALLINT NOT NULL,\n  address_id INT NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY  (store_id),\n  CONSTRAINT fk_store_staff FOREIGN KEY (manager_staff_id) REFERENCES staff (staff_id) ,\n  CONSTRAINT fk_store_address FOREIGN KEY (address_id) REFERENCES address (address_id)\n)')
14 ('table', 'payment', 'payment', 63, 'CREATE TABLE payment (\n  payment_id int NOT NULL,\n  customer_id INT  NOT NULL,\n  staff_id SMALLINT NOT NULL,\n  rental_id INT DEFAULT NULL,\n  amount DECIMAL(5,2) NOT NULL,\n  payment_date TIMESTAMP NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY  (payment_id),\n  CONSTRAINT fk_payment_rental FOREIGN KEY (rental_id) REFERENCES rental (rental_id) ON DELETE SET NULL ON UPDATE CASCADE,\n  CONSTRAINT fk_payment_customer FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ,\n  CONSTRAINT fk_payment_staff FOREIGN KEY (staff_id) REFERENCES staff (staff_id)\n)')
15 ('table', 'rental', 'rental', 69, 'CREATE TABLE rental (\n  rental_id INT NOT NULL,\n  rental_date TIMESTAMP NOT NULL,\n  inventory_id INT  NOT NULL,\n  customer_id INT  NOT NULL,\n  return_date TIMESTAMP DEFAULT NULL,\n  staff_id SMALLINT  NOT NULL,\n  last_update TIMESTAMP NOT NULL,\n  PRIMARY KEY (rental_id),\n  CONSTRAINT fk_rental_staff FOREIGN KEY (staff_id) REFERENCES staff (staff_id) ,\n  CONSTRAINT fk_rental_inventory FOREIGN KEY (inventory_id) REFERENCES inventory (inventory_id) ,\n  CONSTRAINT fk_rental_customer FOREIGN KEY (customer_id) REFERENCES customer (customer_id)\n)')

# Selecting and Retrieving Data:

Let's look at the `actor` table and retrieve all the data

In [9]:
cursor = connection_db.execute('''
SELECT *
FROM actor
LIMIT 5;  -- the first 5 rows from the actor table
''')
actors = cursor.fetchall()  ## fetch all the results returned by the query (list of table names)
print('Number of records retrieved: ', len(actors))

Number of records retrieved:  5

In [10]:
# Showing items:
for idx,emp in enumerate(actors):  ## enumerate() adds an index to each element in the list actors 
    print(idx,emp)

0 (1, 'PENELOPE', 'GUINESS', '2020-12-23 07:12:29')
1 (2, 'NICK', 'WAHLBERG', '2020-12-23 07:12:29')
2 (3, 'ED', 'CHASE', '2020-12-23 07:12:29')
3 (4, 'JENNIFER', 'DAVIS', '2020-12-23 07:12:29')
4 (5, 'JOHNNY', 'LOLLOBRIGIDA', '2020-12-23 07:12:29')

#### Another way is to store in a pandas datframe

In [12]:
actors_df_1 = pd.read_sql("""SELECT *
                             FROM actor;""", connection_db)
print(type(actors_df_1))
print('\n', actors_df_1.shape)
print('\n', actors_df_1.dtypes)

<class 'pandas.core.frame.DataFrame'>

 (200, 4)

 actor_id        int64
first_name     object
last_name      object
last_update    object
dtype: object

In [13]:
actors_df_1.head()  ## show the first 5 rows from the actor table

   actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2020-12-23 07:12:29
1         2       NICK      WAHLBERG  2020-12-23 07:12:29
2         3         ED         CHASE  2020-12-23 07:12:29
3         4   JENNIFER         DAVIS  2020-12-23 07:12:29
4         5     JOHNNY  LOLLOBRIGIDA  2020-12-23 07:12:29

#### Now we will select only `actor_id`, `first_name` and `last_name`

In [14]:
actors_df_2 = pd.read_sql("""SELECT actor_id, first_name, last_name
                             FROM actor;""", connection_db)
actors_df_2.head()

   actor_id first_name     last_name
0         1   PENELOPE       GUINESS
1         2       NICK      WAHLBERG
2         3         ED         CHASE
3         4   JENNIFER         DAVIS
4         5     JOHNNY  LOLLOBRIGIDA

* Commas after each column name is essential and without them the code will throw an error. Alternative way to write query is as below. This looks better and ensures you have the comma in the beginning of each line.

In [15]:
actors_df_3= pd.read_sql("""SELECT actor_id
                                 , first_name
                                 , last_name
                            FROM actor;""", connection_db)
actors_df_3.head()

   actor_id first_name     last_name
0         1   PENELOPE       GUINESS
1         2       NICK      WAHLBERG
2         3         ED         CHASE
3         4   JENNIFER         DAVIS
4         5     JOHNNY  LOLLOBRIGIDA

#### Note: SQLite is case insensitive. Changing `actor_id` to `ACTOR_ID` will give same result.

In [16]:
actors_df_4= pd.read_sql("""SELECT ACTOR_ID    
                                 , first_name
                                 , last_name
                            FROM actor;""", connection_db)
actors_df_4.head()

   actor_id first_name     last_name
0         1   PENELOPE       GUINESS
1         2       NICK      WAHLBERG
2         3         ED         CHASE
3         4   JENNIFER         DAVIS
4         5     JOHNNY  LOLLOBRIGIDA

## Filtering:

*   Filtering helps make data retrieval more specific
*   reduce number of records
*   Increase query performance
*   Reduce strain on client applications

#### Filtering using `WHERE` clause:

In [17]:
actors_df_5 = pd.read_sql("""SELECT *
                             FROM actor
                             WHERE first_name = "JENNIFER";""", connection_db)
print(actors_df_5.shape)
actors_df_5.head()

(1, 4)

   actor_id first_name last_name          last_update
0         4   JENNIFER     DAVIS  2020-12-23 07:12:29

#### Checking non matches

In [18]:
actors_df_5 = pd.read_sql("""SELECT *
                             FROM actor
                             WHERE first_name != "JENNIFER";""", connection_db)
print(actors_df_5.shape)
actors_df_5.head()

(199, 4)

   actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2020-12-23 07:12:29
1         2       NICK      WAHLBERG  2020-12-23 07:12:29
2         3         ED         CHASE  2020-12-23 07:12:29
3         5     JOHNNY  LOLLOBRIGIDA  2020-12-23 07:12:29
4         6      BETTE     NICHOLSON  2020-12-23 07:12:29

In [19]:
actors_df_5 = pd.read_sql("""SELECT *, (first_name != "JENNIFER") AS non_matches
                             FROM actor;""", connection_db)
print(actors_df_5.shape)
actors_df_5.head()

(200, 5)

   actor_id first_name     last_name          last_update  non_matches
0         1   PENELOPE       GUINESS  2020-12-23 07:12:29            1
1         2       NICK      WAHLBERG  2020-12-23 07:12:29            1
2         3         ED         CHASE  2020-12-23 07:12:29            1
3         4   JENNIFER         DAVIS  2020-12-23 07:12:29            0
4         5     JOHNNY  LOLLOBRIGIDA  2020-12-23 07:12:29            1

In [20]:
actors_df_5 = pd.read_sql("""SELECT *, (first_name != "JENNIFER") = TRUE AS non_matches
                             FROM actor;""", connection_db)
print(actors_df_5.shape)
actors_df_5.head()

(200, 5)

   actor_id first_name     last_name          last_update  non_matches
0         1   PENELOPE       GUINESS  2020-12-23 07:12:29            1
1         2       NICK      WAHLBERG  2020-12-23 07:12:29            1
2         3         ED         CHASE  2020-12-23 07:12:29            1
3         4   JENNIFER         DAVIS  2020-12-23 07:12:29            0
4         5     JOHNNY  LOLLOBRIGIDA  2020-12-23 07:12:29            1

#### Reading payment data

In [21]:
payment_df_1 = pd.read_sql("""SELECT *
                              FROM payment""", connection_db)
print(payment_df_1.shape)
payment_df_1.head()

(16049, 7)

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update
0,1,1,1,76.0,2.99,2005-05-25 11:30:37.000,2020-12-23 07:19:10
1,2,1,1,573.0,0.99,2005-05-28 10:35:23.000,2020-12-23 07:19:10
2,3,1,1,1185.0,5.99,2005-06-15 00:54:12.000,2020-12-23 07:19:10
3,4,1,2,1422.0,0.99,2005-06-15 18:02:53.000,2020-12-23 07:19:10
4,5,1,2,1476.0,9.99,2005-06-15 21:08:46.000,2020-12-23 07:19:10

#### Filtering values within a range

In [22]:
payment_df_2 = pd.read_sql("""SELECT *
                              FROM payment
                              WHERE amount BETWEEN 1 AND 5""", connection_db)
print(payment_df_2.shape)
payment_df_2.head()

(9089, 7)

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update
0,1,1,1,76.0,2.99,2005-05-25 11:30:37.000,2020-12-23 07:19:10
1,6,1,1,1725.0,4.99,2005-06-16 15:18:57.000,2020-12-23 07:19:10
2,7,1,1,2308.0,4.99,2005-06-18 08:41:48.000,2020-12-23 07:19:10
3,9,1,1,3284.0,3.99,2005-06-21 06:24:45.000,2020-12-23 07:19:10
4,12,1,1,5244.0,4.99,2005-07-09 13:24:07.000,2020-12-23 07:19:10

In [23]:
payment_df_2 = pd.read_sql("""SELECT *
                              FROM payment
                              WHERE amount BETWEEN 3.99 AND 4.99""", connection_db)
print(payment_df_2.shape)
payment_df_2.head()

(4898, 7)

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update
0,6,1,1,1725.0,4.99,2005-06-16 15:18:57.000,2020-12-23 07:19:10
1,7,1,1,2308.0,4.99,2005-06-18 08:41:48.000,2020-12-23 07:19:10
2,9,1,1,3284.0,3.99,2005-06-21 06:24:45.000,2020-12-23 07:19:10
3,12,1,1,5244.0,4.99,2005-07-09 13:24:07.000,2020-12-23 07:19:10
4,13,1,1,5326.0,4.99,2005-07-09 16:38:01.000,2020-12-23 07:19:10

### Advanced Filtering: `IN`, `OR`, `NOT`

Let's use the payments database to select particular customers.

* `IN` specifies a range of conditions. Uses a comma delimited set of values enclosed in ()

In [24]:
payment_df_3 = pd.read_sql("""SELECT *
                        FROM payment
                        WHERE customer_id IN (1,2,3)""", connection_db)
print(payment_df_3.shape)
payment_df_3.head()

(85, 7)

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update
0,1,1,1,76,2.99,2005-05-25 11:30:37.000,2020-12-23 07:19:10
1,2,1,1,573,0.99,2005-05-28 10:35:23.000,2020-12-23 07:19:10
2,3,1,1,1185,5.99,2005-06-15 00:54:12.000,2020-12-23 07:19:10
3,4,1,2,1422,0.99,2005-06-15 18:02:53.000,2020-12-23 07:19:10
4,5,1,2,1476,9.99,2005-06-15 21:08:46.000,2020-12-23 07:19:10

* `OR` operator: The DBMS will not evaluate second condition if first condition is met.

In [25]:
actors_df_7 = pd.read_sql("""SELECT *
                             FROM actor
                             WHERE first_name = "ED" OR last_name = "CHASE";""", connection_db)
print(actors_df_7.shape)
actors_df_7

(4, 4)

   actor_id first_name  last_name          last_update
0         3         ED      CHASE  2020-12-23 07:12:29
1       136         ED  MANSFIELD  2020-12-23 07:12:30
2       176        JON      CHASE  2020-12-23 07:12:31
3       179         ED    GUINESS  2020-12-23 07:12:31

In [26]:
actors_df_7 = pd.read_sql("""SELECT *
                             FROM actor
                             WHERE first_name = "ED" OR first_name = "NICK";""", connection_db)
print(actors_df_7.shape)
actors_df_7

(6, 4)

   actor_id first_name  last_name          last_update
0         2       NICK   WAHLBERG  2020-12-23 07:12:29
1         3         ED      CHASE  2020-12-23 07:12:29
2        44       NICK   STALLONE  2020-12-23 07:12:29
3       136         ED  MANSFIELD  2020-12-23 07:12:30
4       166       NICK  DEGENERES  2020-12-23 07:12:31
5       179         ED    GUINESS  2020-12-23 07:12:31

In [27]:
actors_df_6 = pd.read_sql("""SELECT *
                             FROM actor
                             WHERE first_name = "ED" OR "NICK";""", connection_db)  ## pay attention: this doesn't give the same result 
print(actors_df_6.shape)
actors_df_6

(3, 4)

   actor_id first_name  last_name          last_update
0         3         ED      CHASE  2020-12-23 07:12:29
1       136         ED  MANSFIELD  2020-12-23 07:12:30
2       179         ED    GUINESS  2020-12-23 07:12:31

In [28]:
actors_df_8 = pd.read_sql("""SELECT *
                        FROM actor
                        WHERE first_name IN ("ED", "NICK");""", connection_db)  ## alternative: using IN
print(actors_df_8.shape)
actors_df_8

(6, 4)

   actor_id first_name  last_name          last_update
0         2       NICK   WAHLBERG  2020-12-23 07:12:29
1         3         ED      CHASE  2020-12-23 07:12:29
2        44       NICK   STALLONE  2020-12-23 07:12:29
3       136         ED  MANSFIELD  2020-12-23 07:12:30
4       166       NICK  DEGENERES  2020-12-23 07:12:31
5       179         ED    GUINESS  2020-12-23 07:12:31

### Note: IN works the same as OR

Benefits of IN:
* Long list of options
* IN executes faster than OR
* Don't have to think about the order with IN
* Can contain another SELECT

### SQL processes `AND` before `OR`
Use (). Don't rely on default ordering. Being specific and using () is the best practice!!

In [29]:
payment_df_4 = pd.read_sql("""SELECT *
                              FROM payment
                              WHERE customer_id = 1 OR customer_id = 2 AND STAFF_ID = 1""", connection_db)
print(payment_df_4.shape)
payment_df_4[30:35]

(47, 7)

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update
30,31,1,2,15298,2.99,2005-08-22 19:41:37.000,2020-12-23 07:19:10
31,32,1,1,15315,5.99,2005-08-22 20:03:46.000,2020-12-23 07:19:10
32,33,2,1,320,4.99,2005-05-27 00:09:24.000,2020-12-23 07:19:10
33,34,2,1,2128,2.99,2005-06-17 20:54:58.000,2020-12-23 07:19:10
34,35,2,1,5636,2.99,2005-07-10 06:31:24.000,2020-12-23 07:19:10

In [30]:
payment_df_5 = pd.read_sql("""SELECT *
                        FROM payment
                        WHERE (customer_id = 1 OR customer_id = 2) AND STAFF_ID = 1""", connection_db)
print(payment_df_5.shape)
payment_df_5[15:20]

(32, 7)

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update
15,30,1,1,14825,1.99,2005-08-22 01:27:57.000,2020-12-23 07:19:10
16,32,1,1,15315,5.99,2005-08-22 20:03:46.000,2020-12-23 07:19:10
17,33,2,1,320,4.99,2005-05-27 00:09:24.000,2020-12-23 07:19:10
18,34,2,1,2128,2.99,2005-06-17 20:54:58.000,2020-12-23 07:19:10
19,35,2,1,5636,2.99,2005-07-10 06:31:24.000,2020-12-23 07:19:10

#### `NOT` used for negation
Below code same as `first_name != "JENNIFER".

In [31]:
actors_df_9 = pd.read_sql("""SELECT *
                             FROM actor
                             WHERE NOT first_name = "JENNIFER";""", connection_db)
print(actors_df_9.shape)
actors_df_9.head()

(199, 4)

   actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2020-12-23 07:12:29
1         2       NICK      WAHLBERG  2020-12-23 07:12:29
2         3         ED         CHASE  2020-12-23 07:12:29
3         5     JOHNNY  LOLLOBRIGIDA  2020-12-23 07:12:29
4         6      BETTE     NICHOLSON  2020-12-23 07:12:29

In [32]:
actors_df_9 = pd.read_sql("""SELECT *
                             FROM actor
                             WHERE first_name != "JENNIFER";""", connection_db)
print(actors_df_9.shape)
actors_df_9.head()

(199, 4)

   actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2020-12-23 07:12:29
1         2       NICK      WAHLBERG  2020-12-23 07:12:29
2         3         ED         CHASE  2020-12-23 07:12:29
3         5     JOHNNY  LOLLOBRIGIDA  2020-12-23 07:12:29
4         6      BETTE     NICHOLSON  2020-12-23 07:12:29

## Using Wildcards

* A wildcard character is used to substitute one or more characters in a string.
  
* Wildcard characters are used with the LIKE operator.
  
* The LIKE operator is used in a WHERE clause to search for a specified pattern in a column.

#### List of wildcards:

| Symbol | Description|
|--------|--------------------------------------------------------------|
| %      | Represents zero or more characters                           |
| _      | Represents a single character                                |
| []     | Represents any single character within the brackets *        |
| ^      | Represents any character not in the brackets *               |
| -      | Represents any single character within the specified range * |
| {}     | Represents any escaped character **                          |

In [33]:
# Using % wildcard: Select names starting with E

actors_df_10 = pd.read_sql("""SELECT *
                              FROM actor
                              WHERE first_name LIKE "E%";""", connection_db)  ## % represents zero or more characters
print(actors_df_10.shape)
actors_df_10

(7, 4)

   actor_id first_name  last_name          last_update
0         3         ED      CHASE  2020-12-23 07:12:29
1        22      ELVIS       MARX  2020-12-23 07:12:29
2        93      ELLEN    PRESLEY  2020-12-23 07:12:30
3       136         ED  MANSFIELD  2020-12-23 07:12:30
4       139       EWAN    GOODING  2020-12-23 07:12:30
5       148      EMILY        DEE  2020-12-23 07:12:30
6       179         ED    GUINESS  2020-12-23 07:12:31

In [34]:
# Using % wildcard: Selecting names starting with E and ending with N

actors_df_11 = pd.read_sql("""SELECT *
                              FROM actor
                              WHERE first_name LIKE "E%N";""", connection_db)  ## % represents zero or more characters
print(actors_df_11.shape)
actors_df_11.head()

(2, 4)

   actor_id first_name last_name          last_update
0        93      ELLEN   PRESLEY  2020-12-23 07:12:30
1       139       EWAN   GOODING  2020-12-23 07:12:30

In [35]:
# Using % wildcard: Selecting names starting with E and containing L

actors_df_11 = pd.read_sql("""SELECT *
                              FROM actor
                              WHERE first_name LIKE "E%L%";""", connection_db)  ## % represents zero or more characters
print(actors_df_11.shape)
actors_df_11

(3, 4)

   actor_id first_name last_name          last_update
0        22      ELVIS      MARX  2020-12-23 07:12:29
1        93      ELLEN   PRESLEY  2020-12-23 07:12:30
2       148      EMILY       DEE  2020-12-23 07:12:30

In [36]:
# Using _ wildcard: Select names ending with D and having 2 letters

actors_df_12 = pd.read_sql("""SELECT *
                              FROM actor
                              WHERE first_name LIKE "_D";""", connection_db)  ## _ represents a single character
print(actors_df_12.shape)
actors_df_12.head()

(3, 4)

   actor_id first_name  last_name          last_update
0         3         ED      CHASE  2020-12-23 07:12:29
1       136         ED  MANSFIELD  2020-12-23 07:12:30
2       179         ED    GUINESS  2020-12-23 07:12:31

#### For `_` wildcard one has to be specific

In [37]:
# Using _ wildcard: Select names ending with A and having 5 letters

actors_df_13 = pd.read_sql("""SELECT *
                              FROM actor
                              WHERE first_name LIKE "____A";""", connection_db)  ## _ represents a single character
print(actors_df_13.shape)
actors_df_13

(11, 4)

    actor_id first_name  last_name          last_update
0         27      JULIA    MCQUEEN  2020-12-23 07:12:29
1         33      MILLA       PECK  2020-12-23 07:12:29
2         47      JULIA  BARRYMORE  2020-12-23 07:12:29
3         74      MILLA     KEITEL  2020-12-23 07:12:29
4        122      SALMA      NOLTE  2020-12-23 07:12:30
5        130      GRETA     KEITEL  2020-12-23 07:12:30
6        157      GRETA     MALDEN  2020-12-23 07:12:31
7        159      LAURA      BRODY  2020-12-23 07:12:31
8        186      JULIA  ZELLWEGER  2020-12-23 07:12:31
9        199      JULIA    FAWCETT  2020-12-23 07:12:31
10       200      THORA     TEMPLE  2020-12-23 07:12:31

#### Note: All DBMS does not have the same wildcards. Some of these wildcards may or may not exist in a particular DBMS. Be wary of the wildcards allowed in a DBMS.

## Sort: Order by

The `ORDER BY` command is used to sort the result set in ascending or descending order.

The `ORDER BY` command sorts the result set in ascending order by default. To sort the records in descending order, use the `DESC` keyword.

* Data displayed appears in the order of the
underlying tables.
* Updated and deleted data can change this
order.
* Sequence of retrieved data cannot be
assumed if order was not specified.
* Sorting data logically helps keep
information you want on top.
* ORDER BY clause allows user to sort data
by particular columns.

### Rules of order by:
* Takes the name of one or more columns
* Add a comma after each additional column
name
* Can sort by a column not retrieved
* Can be sorted using column position

In [38]:
actors_df_14 = pd.read_sql("""SELECT *
                              FROM actor
                              ORDER BY first_name, last_name;""", connection_db)
print(actors_df_14.shape)
actors_df_14.head(6)

(200, 4)

   actor_id first_name  last_name          last_update
0        71       ADAM      GRANT  2020-12-23 07:12:29
1       132       ADAM     HOPPER  2020-12-23 07:12:30
2       165         AL    GARLAND  2020-12-23 07:12:31
3       173       ALAN   DREYFUSS  2020-12-23 07:12:31
4       146     ALBERT  JOHANSSON  2020-12-23 07:12:30
5       125     ALBERT      NOLTE  2020-12-23 07:12:30

#### Sorting with ASC in one and DESC in other

In [39]:
actors_df_15 = pd.read_sql("""SELECT *
                              FROM actor
                              ORDER BY first_name, last_name DESC;""", connection_db)
print(actors_df_15.shape)
actors_df_15.head(6)

(200, 4)

   actor_id first_name  last_name          last_update
0       132       ADAM     HOPPER  2020-12-23 07:12:30
1        71       ADAM      GRANT  2020-12-23 07:12:29
2       165         AL    GARLAND  2020-12-23 07:12:31
3       173       ALAN   DREYFUSS  2020-12-23 07:12:31
4       125     ALBERT      NOLTE  2020-12-23 07:12:30
5       146     ALBERT  JOHANSSON  2020-12-23 07:12:30

#### Depends on the order of the column!

In [40]:
actors_df_15 = pd.read_sql("""SELECT *
                              FROM actor
                              ORDER BY last_name DESC, first_name;""", connection_db)
print(actors_df_15.shape)
actors_df_15.head()

(200, 4)

   actor_id first_name  last_name          last_update
0       111    CAMERON  ZELLWEGER  2020-12-23 07:12:30
1       186      JULIA  ZELLWEGER  2020-12-23 07:12:31
2        85     MINNIE  ZELLWEGER  2020-12-23 07:12:30
3        63    CAMERON       WRAY  2020-12-23 07:12:29
4       156        FAY       WOOD  2020-12-23 07:12:31

#### Use the column position appearing in the SELECT statement 

The positional index for the first column in the SELECT statement is 1, the second is 2, etc.

In [41]:
actors_df_15 = pd.read_sql("""SELECT *
                              FROM actor
                              ORDER BY 3 DESC, 2;""", connection_db)
print(actors_df_15.shape)
actors_df_15.head()

(200, 4)

   actor_id first_name  last_name          last_update
0       111    CAMERON  ZELLWEGER  2020-12-23 07:12:30
1       186      JULIA  ZELLWEGER  2020-12-23 07:12:31
2        85     MINNIE  ZELLWEGER  2020-12-23 07:12:30
3        63    CAMERON       WRAY  2020-12-23 07:12:29
4       156        FAY       WOOD  2020-12-23 07:12:31

#### Can sort by a column not retrieved

In [42]:
actors_df_15 = pd.read_sql("""SELECT actor_id, last_update
                              FROM actor
                              ORDER BY last_name DESC, first_name;""", connection_db)
print(actors_df_15.shape)
actors_df_15.head()

(200, 2)

   actor_id          last_update
0       111  2020-12-23 07:12:30
1       186  2020-12-23 07:12:31
2        85  2020-12-23 07:12:30
3        63  2020-12-23 07:12:29
4       156  2020-12-23 07:12:31

## Math Operations:

#### Order of operations:
Parentheses <br>
Exponents <br>
Multiplication <br>
Division <br>
Addition <br>
Subtraction <br>

In [43]:
payment_df_6 = pd.read_sql("""SELECT *, AMOUNT*0.9 as amount_eur
                              FROM payment;""", connection_db)
print(payment_df_6.shape)
payment_df_6.head()

(16049, 8)

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update,amount_eur
0,1,1,1,76.0,2.99,2005-05-25 11:30:37.000,2020-12-23 07:19:10,2.691
1,2,1,1,573.0,0.99,2005-05-28 10:35:23.000,2020-12-23 07:19:10,0.891
2,3,1,1,1185.0,5.99,2005-06-15 00:54:12.000,2020-12-23 07:19:10,5.391
3,4,1,2,1422.0,0.99,2005-06-15 18:02:53.000,2020-12-23 07:19:10,0.891
4,5,1,2,1476.0,9.99,2005-06-15 21:08:46.000,2020-12-23 07:19:10,8.991

For those who are interested in MySQL, you can find a list of SQL functions here:
https://www.w3schools.com/sql/sql_ref_mysql.asp

Note: These are mysql functions. All of them may not be available for Sqlite

## Aggregate Functions:

An aggregate function is a function that performs a calculation on a set of values, and returns a single value.

The most commonly used SQL aggregate functions are:

MIN() - returns the smallest value within the selected column <br>
MAX() - returns the largest value within the selected column <br>
COUNT() - returns the number of rows in a set <br>
SUM() - returns the total sum of a numerical column <br>
AVG() - returns the average value of a numerical column <br>

Aggregate functions ignore null values (except for COUNT()).

In [44]:
payment_df_8 = pd.read_sql("""SELECT COUNT(*) as count
                              ,AVG(amount) as avg_amount
                              ,MAX(amount) as max_amount
                              FROM payment;""", connection_db)
print(payment_df_8.shape)
payment_df_8.head()

(1, 3)

   count  avg_amount  max_amount
0  16049    4.200667       11.99

## Grouping Data:

The `GROUP BY` statement groups rows that have the same values into summary rows, like "find the number of customers in each country".

The `GROUP BY` statement is often used with aggregate functions (COUNT(), MAX(), MIN(), SUM(), AVG()) to group the result-set by one or more columns.

In [45]:
payment_df_9 = pd.read_sql("""SELECT customer_id
                              , COUNT(rental_id) as total_dvd_rented
                              , SUM(amount) as total_customer_spent
                              FROM payment
                              GROUP BY customer_id
                              ORDER BY customer_id;""", connection_db)
print(payment_df_9.shape)
payment_df_9.head()

(599, 3)

   customer_id  total_dvd_rented  total_customer_spent
0            1                32                118.68
1            2                27                128.73
2            3                26                135.74
3            4                22                 81.78
4            5                38                144.62

* GROUP BY clauses can contain multiple
columns
* Every column in your SELECT statement
must be present in a GROUP BY clause,
except for aggregated calculations
* NULLs will be grouped together if your
GROUP BY column contains NULLs

* `WHERE` does not work for groups
* `WHERE` filters on rows
* Instead use `HAVING` clause to filter for
groups

In [47]:
payment_df_10 = pd.read_sql("""SELECT customer_id
                               , COUNT(rental_id) as total_dvd_rented
                               , SUM(amount) as total_customer_spent
                               FROM payment
                               GROUP BY customer_id
                               HAVING COUNT(rental_id)<15
                               ORDER BY customer_id;""", connection_db)
print(payment_df_10.shape)
payment_df_10

(4, 3)

   customer_id  total_dvd_rented  total_customer_spent
0           61                14                 58.86
1          110                14                 59.86
2          281                14                 50.86
3          318                12                 52.88

## CASE WHEN:
The `CASE` expression goes through conditions and returns a value when the first condition is met (like an if-then-else statement). 

* Once a condition is true, it will stop reading and return the result. 

* If no conditions are true, it returns the value in the `ELSE` clause.

* If there is no `ELSE` part and no conditions are true, it returns `NULL`.

In [46]:
payment_df_11 = pd.read_sql("""SELECT *,
                               CASE WHEN amount > 5 THEN 'expensive'
                               ELSE 'not_expensive'
                               END as expensive_flag
                               FROM payment;""", connection_db)
print(payment_df_11.shape)
payment_df_11.head()

(16049, 8)

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,last_update,expensive_flag
0,1,1,1,76.0,2.99,2005-05-25 11:30:37.000,2020-12-23 07:19:10,not_expensive
1,2,1,1,573.0,0.99,2005-05-28 10:35:23.000,2020-12-23 07:19:10,not_expensive
2,3,1,1,1185.0,5.99,2005-06-15 00:54:12.000,2020-12-23 07:19:10,expensive
3,4,1,2,1422.0,0.99,2005-06-15 18:02:53.000,2020-12-23 07:19:10,not_expensive
4,5,1,2,1476.0,9.99,2005-06-15 21:08:46.000,2020-12-23 07:19:10,expensive

In [48]:
# closing connection to the database:

connection_db.close()

# Creating Tables:

This part is concerned with creating tables both permanent and temporary. First we will create a new database called `ba_bachelors`

In [49]:
### Creating a new database ###

connection_ba = sqlite3.connect('ba_bachelors.db')

tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", connection_ba)

In [50]:
print(tables['name'])

Series([], Name: name, dtype: object)

In [51]:
## create a cursor object that allows us to interact with the database
cursor_obj = connection_ba.cursor()

In [57]:
# Creating Table:

cursor_obj.execute("DROP TABLE IF EXISTS students") # drop table if already present

students_table = """CREATE TABLE students (
                    student_id VARCHAR(255) PRIMARY KEY
                    , first_Name CHAR(25) NOT NULL
                    , last_Name CHAR(25)
                    , number_courses INT
                    , gpa DECIMAL(8,2)
                 ); """

cursor_obj.execute(students_table)

print("Table is Ready")

Table is Ready

In [58]:
students_df = pd.read_sql("""SELECT *
                             FROM students;""", connection_ba)
students_df

Empty DataFrame
Columns: [student_id, first_Name, last_Name, number_courses, gpa]
Index: []

#### Inserting Data into the students table.

In [59]:
cursor_obj.execute("""
                    INSERT INTO students(
                    student_id
                  , first_Name
                  , last_Name
                  , number_courses
                  , gpa
                    )
                    VALUES (
                    '20240198567'
                  , 'Emily'
                  , 'Smith'
                  , '0'
                  , '7.5'
                    );""")

In [60]:
students_df = pd.read_sql("""SELECT *
                             FROM students;""", connection_ba)
students_df

    student_id first_Name last_Name  number_courses  gpa
0  20240198567      Emily     Smith               0  7.5

#### Need to commit before closing connection!

In [61]:
## commit the current transaction / change
## permanently save all data modifications (e.g., INSERT, UPDATE, DELETE) during the current session to the database
connection_ba.commit()

In [62]:
connection_ba.close()  ## close connection to the database

#### The table still remains!

In [63]:
connection_ba = sqlite3.connect('ba_bachelors.db')

tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", connection_ba)

print(tables['name'])

0    students
Name: name, dtype: object

In [64]:
students_df = pd.read_sql("""SELECT *
                             FROM students;
                          """, connection_ba)
students_df

    student_id first_Name last_Name  number_courses  gpa
0  20240198567      Emily     Smith               0  7.5

#### Creating Temporary tables:

* Temporary tables will be deleted when
current session is terminated
* Faster than creating a real table
* Useful for complex queries using subsets
and joins

In [65]:
# connection_ba = sqlite3.connect("ba_bachelors.db")

cursor_obj = connection_ba.cursor()

idm_table = """ CREATE TEMPORARY TABLE idm_course (  -- try to delete TEMPORARY and see the difference 
                student_id VARCHAR(255) PRIMARY KEY
                , first_Name CHAR(25) NOT NULL
                , last_Name CHAR(25)
                , midterm_grade DECIMAL(8,2)
                , final_grade DECIMAL(8,2)
                ); """

cursor_obj.execute(idm_table)

print("Table is Ready")

Table is Ready

In [66]:
cursor_obj.execute("""
                    INSERT INTO idm_course(
                    student_id
                  , first_Name
                  , last_Name
                  , midterm_grade
                  , final_grade
                    )
                    VALUES (
                    '20240198567'
                  , 'Emily'
                  , 'Smith'
                  , '7'
                  , '8.5'
                    );""")

In [67]:
idm_df = pd.read_sql("""SELECT *
                        FROM idm_course;""", connection_ba)
idm_df

    student_id first_Name last_Name  midterm_grade  final_grade
0  20240198567      Emily     Smith              7          8.5

In [68]:
connection_ba.commit()  ## commit the current change
connection_ba.close()   ## close connection to the database

#### Now let's conenct to the Database and check what tables exist

In [69]:
connection_ba = sqlite3.connect('ba_bachelors.db')

tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", connection_ba)

print(tables['name'])

0    students
Name: name, dtype: object

In [70]:
connection_ba.close()   ## close connection to the database

In [71]:
import os
os.remove('ba_bachelors.db')  # delete the database file

# Remarks

In [72]:
## connect with a database / create a new example database
connection_example = sqlite3.connect('example.db')

## create a cursor object that allows us to interact with the database
cursor_example = connection_example.cursor()

In [73]:
## create a table
cursor_example.execute("DROP TABLE IF EXISTS study") # drop table if already present

cursor_example.execute(""" CREATE TABLE study (
                           student_id VARCHAR(255) PRIMARY KEY
                           , number_courses INT
                           , gpa DECIMAL(8,2)); """)

In [74]:
## create a DataFrame which contains metadata about the tables
tables_example = pd.read_sql("""SELECT *
                                FROM sqlite_master
                                WHERE type='table';""", connection_example)
print(tables_example['name'])

0    study
Name: name, dtype: object

In [75]:
## insert values to the table
cursor_example.execute("""INSERT INTO study (student_id, number_courses, gpa)
                          VALUES ('20240198567', '0', '7.5'), ('20240198568', 9, NULL), (NULL, NULL, NULL);""")

In [76]:
## have a look at the table
study_example = pd.read_sql("""SELECT *
                               FROM study;""", connection_example)
print(study_example.dtypes)
print("\n")
print(study_example)

student_id         object
number_courses    float64
gpa               float64
dtype: object


    student_id  number_courses  gpa
0  20240198567             0.0  7.5
1  20240198568             9.0  NaN
2         None             NaN  NaN

In [77]:
## execute a query with COUNT(*)
count_all_rows = pd.read_sql("SELECT COUNT(*) AS count_all FROM study", connection_example)
count_all_rows

   count_all
0          3

In [78]:
## execute a query with COUNT(a column name) 
count_column1 = pd.read_sql("SELECT COUNT(number_courses) AS count_column1 FROM study", connection_example)
count_column1

   count_column1
0              2

In [79]:
## execute a query with COUNT(a column name) 
count_column2 = pd.read_sql("SELECT COUNT(gpa) AS count_column2 FROM study", connection_example)
count_column2

   count_column2
0              1

In [80]:
## close the connection
connection_example.close()